from components.compartment_curves import CompartmentCurves
from components.marginal_heatmap import MarginalHeatmap
from components.marginal_scatter import MarginalScatter
from components.compartment_lines import CompartmentLines
